# Lab 6: Data Transformation | Treasure Hunt Dataset
Name: **Krish Agarwal** <br>
Reg No: **21112016** <br>
Class: **3BSc DS A** <br>

---------------

## **Objective**:  
Performing an Exploratory Data Analysis on the data collected post Treasure Hunt conducted by Data Science Association.

## **Problem Definition**:  
Trying to find interesting patterns through the usage of Matplotlib, Seaborn, and other visualisation libraries.

## **Approach/Method**:  
Using of logical indexing and functions provided by MatPlotLib and Seaborn Library to make meaningful insights from the dataset via Visualization.

## **Results**:  
Many inferences can be made from the dataset generated by the Treasure Hunt conducted by the Data Science Association viz number of winners from each class, students in each class, Male to Female Ratio, etc. Above are the few insights made by me.

## **Learning and Reflections**:

After performing the given task, I would say I am confident enough in logical and double indexing now. And with the research done foe completing the above inferences, I came across other multiple functions provided by the Pandas, Matplotlib and Seaborn Library.

## **Refrences**:  

1. https://stackoverflow.com/questions/37787698/how-to-sort-pandas-dataframe-from-one-column  
1. https://cherono-mj.medium.com/importing-and-exporting-datasets-to-and-from-a-google-colab-python-81fbf8a32c84  
1. https://www.activestate.com/resources/quick-reads/how-to-delete-a-column-row-from-a-dataframe/#:~:text=You%20can%20use%20the%20drop,columns%20in%20a%20Pandas%20DataFrame.  
1. https://www.geeksforgeeks.org/pandas-how-to-reset-index-in-a-given-dataframe/  
1. https://www.geeksforgeeks.org/adding-new-column-to-existing-dataframe-in-pandas/  
1. https://www.google.com/search?q=how+to+create+a+new+columnin+dataframe+%5C&rlz=1C1UEAD_enIN969IN969&oq=how+to+create+a+new+columnin+dataframe+%5C&aqs=chrome..69i57j0i13i512l9.8341j0j7&sourceid=chrome&ie=UTF-8  
1. https://datatofish.com/replace-nan-values-with-zeros/  
1. https://www.geeksforgeeks.org/python-pandas-extracting-rows-using-loc/  
1. https://www.geeksforgeeks.org/extract-specific-column-from-a-dataframe-using-column-name-in-r/  
1. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html  
1. https://www.geeksforgeeks.org/replace-nan-values-with-zeros-in-pandas-dataframe/  
1. https://www.geeksforgeeks.org/python-pandas-dataframe-isna/  
1. https://www.w3schools.com/python/pandas/ref_df_mask.asp#:~:text=The%20mask()%20method%20replaces,the%20The%20where()%20method.  
1. https://www.tutorialspoint.com/how-to-get-the-mean-of-columns-that-contains-numeric-values-of-a-dataframe-in-pandas-python  
1. https://www.geeksforgeeks.org/plot-a-pie-chart-in-python-using-matplotlib/  
1. https://stackoverflow.com/questions/21572870/matplotlib-percent-label-position-in-pie-chart  
1. https://stackoverflow.com/questions/47269695/plotting-categorical-variable-against-numeric-variable-in-matplotlib  
1. http://seaborn.pydata.org/generated/seaborn.swarmplot.html#seaborn.swarmplot  
1. https://plotly.com/python/  
1. https://www.geeksforgeeks.org/plotting-histogram-in-python-using-matplotlib/  
1. https://www.geeksforgeeks.org/bar-plot-in-matplotlib/  
1. https://stackoverflow.com/questions/36719385/python-group-two-lists  
1. https://seaborn.pydata.org/tutorial/categorical.html  
1. https://stackoverflow.com/questions/53460051/convert-ipynb-notebook-to-html-in-google-colab  
1. https://stackoverflow.com/questions/60650617/error-while-running-profiling-report-using-pandas-giving-me-an-error-typeerror  
1. https://pandas-profiling.ydata.ai/docs/master/pages/getting_started/quickstart.html#command-line-usage  
1. https://towardsdatascience.com/data-normalization-with-python-scikit-learn-e9c5640fed58  
1. https://scikit-learn.org/stable/modules/preprocessing.html  
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

## **Code**:

### --- Importing necessary libraries ---

In [4]:
# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import groupby
from operator import itemgetter
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from pandas_profiling import ProfileReport

### --- Importing Dataset onto Python ---

In [5]:
df = pd.read_excel('D:/Z/Downloads/TreasureHuntDataset.xlsx')

In [6]:
df

,Timestamp,Name,Class,Register Number,Gender,We made _______ during the event,Final Position,"On a scale of 1 to 5, How much did you like the event?",Did you find the Clues Difficult?,Did you find the First Round (Quiz) Easy?,...,How many team mates did you know before?,How many of you were in the Team?,How many team mates spoke the same language as yours?,Count of Team Mates from 1 BSc EA,Count of Team Mates from 1 BSc DS,Count of Team Mates from 3 BSc EA,Count of Team Mates from 3 BSc DS,Count of Team Mates from 5 BSc EA,Count of Team Mates from 5 BSc DS,Count of Team Mates from MSc
0,2022-09-06 16:25:46.465,Sampatha Kollara,3 BSc EA,21112330.0,Female,WhatsApp Group,Out after Prelims,5.0,5.0,5.0,...,-,1.0,-,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,2022-09-06 16:25:53.006,Rahul Gnanapandithan,3 BSc EA,21112322.0,Male,"Phone Calls, Text Message, WhatsApp Group, Ver...",Out after Prelims,3.0,3.0,3.0,...,volunteers,1.0,volunteers,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,2022-09-06 16:26:53.754,rishi menon,3 BSc EA,-,Male,-,Out after Prelims,5.0,5.0,5.0,...,-,2.0,-,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,2022-09-08 18:14:18.589,Sudiksha,3 BSc EA,21112342.0,Female,Verbal Communication,Out after Prelims,4.0,2.0,2.0,...,2.0,5.0,5.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0
4,2022-09-08 18:14:34.625,Rishi Menon,3 BSc EA,21112326.0,Male,"WhatsApp Group, Verbal Communication",Volunteer,5.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2022-09-15 19:23:29.750,Sangeeta P,3 BSc DS,21112018.0,Female,"Verbal Communication, Played an online game",Out after Prelims,4.0,3.0,5.0,...,2.0,5.0,Everyone spoke in English,0.0,2.0,0.0,2.0,0.0,1.0,0.0
58,2022-09-22 13:59:34.665,Abhishek Tiwari,3 BSc DS,21112038.0,Male,WhatsApp Group,II Place,3.0,2.0,5.0,...,Zero,4.0,Everyone,0.0,1.0,0.0,1.0,0.0,0.0,2.0
59,2022-09-24 22:11:29.851,Shubhaansh Kumar Shubh,3 BSc EA,21112337.0,Male,"WhatsApp Group, Verbal Communication",Out after Prelims,5.0,5.0,5.0,...,------Null,1.0,------Null,1.0,1.0,1.0,1.0,1.0,1.0,1.0
60,2022-09-27 11:48:11.471,Shreyansh Padarha,3 BSc DS,21112026.0,Male,"Phone Calls, WhatsApp Group, Verbal Communication",Out after Prelims,4.0,5.0,3.0,...,1.0,4.0,All,0.0,1.0,0.0,2.0,0.0,0.0,1.0
61,2022-09-28 09:56:32.803,shreya,3 BSc EA,21112357.0,Female,"Phone Calls, Verbal Communication",Out after Prelims,5.0,4.0,1.0,...,2.0,5.0,5.0,0.0,0.0,3.0,0.0,0.0,0.0,2.0

### --- Data Wrangling ---

#### Removing Rows with invalid Registration Numbers

In [7]:
df.drop(2,axis=0,inplace=True)

#### Sorting the DataFrame on the basis of Registration Number

In [8]:
# Converting the data type to integer
df['Register Number'] = df['Register Number'].astype(int)

In [9]:
df = df.sort_values(by=['Register Number'], ascending=True)

In [10]:
# As we have removed an instance from the data frame, we reset the index
df.reset_index(inplace = True, drop = True)

#### Removing of invalid and multiple entries of Registration Number

Note: 1. We are keeping the most recent entry on the basis of timestamp and removing other entries under the same registration numbers.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. We are also keeping entries with not NaN values in case of multiple entries to make better insights.

In [11]:
duplicate = df[df.duplicated(['Register Number'])]

In [12]:
duplicate

,Timestamp,Name,Class,Register Number,Gender,We made _______ during the event,Final Position,"On a scale of 1 to 5, How much did you like the event?",Did you find the Clues Difficult?,Did you find the First Round (Quiz) Easy?,...,How many team mates did you know before?,How many of you were in the Team?,How many team mates spoke the same language as yours?,Count of Team Mates from 1 BSc EA,Count of Team Mates from 1 BSc DS,Count of Team Mates from 3 BSc EA,Count of Team Mates from 3 BSc DS,Count of Team Mates from 5 BSc EA,Count of Team Mates from 5 BSc DS,Count of Team Mates from MSc
4,2022-09-15 12:08:42.878,Dhairyashil Mahadik,3 BSc DS,21112006,Male,"Phone Calls, Verbal Communication",Out after Prelims,2.0,2.0,4.0,...,One,2.0,None (all English (,0.0,0.0,0.0,1.0,0.0,0.0,0.0
26,2022-09-08 18:14:55.445,Advik Sinha,3 BSc EA,21112302,Male,"WhatsApp Group, Verbal Communication",III Place,4.0,3.0,5.0,...,1.0,5.0,5.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0
43,2022-09-08 18:16:07.067,Sampatha Kollara,3 BSc EA,21112330,Female,WhatsApp Group,Volunteer,5.0,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2022-09-08 18:22:38.987,Shreya Magoo,3 BSc EA,21112357,Female,"Phone Calls, Verbal Communication",Out after Prelims,5.0,4.0,5.0,...,2.0,5.0,5.0,0.0,0.0,3.0,0.0,0.0,0.0,2.0
59,2022-09-08 18:18:43.860,Pari Jain,3 BSc EA,21112360,Female,"Phone Calls, Text Message, WhatsApp Group, Ver...",Out after Prelims,5.0,2.0,5.0,...,2.0,5.0,1.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0
60,2022-09-08 18:16:03.705,Pari Jain,3 BSc EA,21112360,Female,"Phone Calls, Text Message, WhatsApp Group, Ver...",Out after Prelims,5.0,2.0,5.0,...,2.0,5.0,1.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0

In [13]:
# Removing the multiple entries from their index values
df.drop([0, 3, 26, 43, 55, 59, 60],axis=0,inplace=True)

#### Renaming columns

In [14]:
df.rename(columns = {'We made _______ during the event':'Communication'}, inplace = True)
df.rename(columns = {'On a scale of 1 to 5, How much did you like the event?':'Event (/5)'}, inplace = True)
df.rename(columns = {'Did you find the Clues Difficult?':'Clues (/5)'}, inplace = True)
df.rename(columns = {'Did you find the First Round (Quiz) Easy?':'First Round (/5)'}, inplace = True)
df.rename(columns = {'Enter your Team Mates Register Numbers (Separated by Commas)':'Team Mates'}, inplace = True)
df.rename(columns = {'How many team mates did you know before?':'Team Mates Known Prior'}, inplace = True)
df.rename(columns = {'How many of you were in the Team?':'Total Members'}, inplace = True)
df.rename(columns = {'How many team mates spoke the same language as yours?':'Same Language'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 1 BSc EA':'1BSc EA'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 1 BSc DS':'1BSc DS'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 3 BSc EA':'3BSc EA'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 3 BSc DS':'3BSc DS'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 5 BSc EA':'5BSc EA'}, inplace = True)
df.rename(columns = {'Count of Team Mates from 5 BSc DS':'5BSc DS'}, inplace = True)
df.rename(columns = {'Count of Team Mates from MSc':'MSc'}, inplace = True)

In [15]:
df.reset_index(inplace = True, drop = True)

#### Replacing NaN values with 0  
Note: Since a lot of entries consist of NaN values, it could be a tedious task to fill in those values. Hence, we are filling those values simply with 0.

In [16]:
df = df.fillna(0)

#### Cleaning the data column wise

Team Mates Known Prior

In [17]:
df['Team Mates Known Prior'].unique()

array([0.0, 2.0, 'One ', 'NONE', 5.0, 1.0, 'one', 3.0, 'None', 'Zero',
       'none', 4.0, 'volunteers', '-', '------Null'], dtype=object)

In [18]:
# instances that have to be converted into zero
team_prior_zero = ['NONE', 'None', 'Zero', 'none', 'volunteers', '-', '------Null']

In [19]:
# instances that have to be converted into one
team_prior_one = ['One ', 'one']

In [20]:
# the match method replaces the value wit the given value if the condition if satisfied
for i in team_prior_zero:
    df['Team Mates Known Prior'].mask((df['Team Mates Known Prior'] == i) ,0, inplace=True)

In [21]:
for i in team_prior_one:
    df['Team Mates Known Prior'].mask((df['Team Mates Known Prior'] == i) ,0, inplace=True)

Same Language

In [22]:
df['Same Language'].unique()

array([0.0, 5.0, 'None (all English (', 3.0, 'Everyone spoke in English ',
       'One', 'None', 'All', 1.0, 4.0,
       'All have communicated in English sometimes hindi', 'Everyone',
       'All of them', 'all of them', 'Everyone spoke the same language',
       'all 5', 2.0, 'all', 'volunteers', 'Everytime', '-', '------Null',
       'few '], dtype=object)

In [23]:
# instances that have to be converted into zero
same_lang_zero = ['None', 'None (all English (', 'Everyone spoke in English ', 'volunteers', '-', '------Null']

In [24]:
# instances that have to be converted into one
same_lang_one = ['One']

In [25]:
# instances that have to be swapped with their total members 
same_lang_all = ['All', 'All have communicated in English sometimes hindi', 'Everyone', 'All of them', 'all of them', 'Everyone spoke the same language', 'all 5', 'all', 'Everytime']

In [26]:
# instances that have to be swaapped with the average of the column 
same_lang_avg = ['few ']

In [27]:
for i in same_lang_zero:
    df['Same Language'].mask((df['Same Language'] == i) ,0, inplace=True)

In [28]:
for i in same_lang_one:
    df['Same Language'].mask((df['Same Language'] == i) ,1, inplace=True)

In [29]:
for i in same_lang_all:
    df['Same Language'].mask((df['Same Language'] == i) , df['Total Members'], inplace=True)

In [30]:
for i in same_lang_avg:
    df['Same Language'].mask((df['Same Language'] == i) , 3, inplace=True) # 3 being the average of ceil(0+1+...5/6)

#### Changing the data types of the columns

In [31]:
df.dtypes

Timestamp                 datetime64[ns]
Name                              object
Class                             object
Register Number                    int64
Gender                            object
Communication                     object
Final Position                    object
Event (/5)                       float64
Clues (/5)                       float64
First Round (/5)                 float64
Team Mates                        object
Team Mates Known Prior            object
Total Members                    float64
Same Language                     object
1BSc EA                          float64
1BSc DS                          float64
3BSc EA                          float64
3BSc DS                          float64
5BSc EA                          float64
5BSc DS                          float64
MSc                              float64
dtype: object

In [32]:
# Changing the data type of columns to their respective data type
df['Team Mates Known Prior'] = df['Team Mates Known Prior'].astype(int)
df['Total Members'] = df['Total Members'].astype(int)
df['Same Language'] = df['Same Language'].astype(int)
df['1BSc EA'] = df['1BSc EA'].astype(int)
df['1BSc DS'] = df['1BSc DS'].astype(int)
df['3BSc EA'] = df['3BSc EA'].astype(int)
df['3BSc DS'] = df['3BSc DS'].astype(int)
df['5BSc EA'] = df['5BSc EA'].astype(int)
df['5BSc DS'] = df['5BSc DS'].astype(int)
df['MSc'] = df['MSc'].astype(int)

In [33]:
df.dtypes

Timestamp                 datetime64[ns]
Name                              object
Class                             object
Register Number                    int64
Gender                            object
Communication                     object
Final Position                    object
Event (/5)                       float64
Clues (/5)                       float64
First Round (/5)                 float64
Team Mates                        object
Team Mates Known Prior             int64
Total Members                      int64
Same Language                      int64
1BSc EA                            int64
1BSc DS                            int64
3BSc EA                            int64
3BSc DS                            int64
5BSc EA                            int64
5BSc DS                            int64
MSc                                int64
dtype: object

#### Dropping of unnecessary columns

In [34]:
df = df.drop(['Timestamp', 'Team Mates', 'Communication'], axis=1)

In [35]:
df.head()

,Name,Class,Register Number,Gender,Final Position,Event (/5),Clues (/5),First Round (/5),Team Mates Known Prior,Total Members,Same Language,1BSc EA,1BSc DS,3BSc EA,3BSc DS,5BSc EA,5BSc DS,MSc
0,Abhishek Nag,3 BSc DS,21112001,Male,Out after Prelims,2.0,3.0,4.0,0,4,0,0,0,0,0,0,0,3
1,Aman Suhag,3 BSc DS,21112003,Female,Out after Prelims,4.0,2.0,4.0,2,5,5,0,2,0,2,0,1,0
2,Dhairyashil Mahadik,3 BSc DS,21112006,Male,Out after Prelims,2.0,2.0,4.0,0,2,0,0,0,0,1,0,0,0
3,Gaurika,3 BSc DS,21112009,Female,Volunteer,4.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0
4,GULAFSHAN,3 BSc DS,21112010,Female,Out after Prelims,3.0,3.0,3.0,0,5,0,0,0,0,0,3,0,1

#### Label Encoding

In [36]:
# Label Encoding the Gender Column
gender_le = LabelEncoder()
df['Gender'] = gender_le.fit_transform(df['Gender']) # Female --> 0, Male --> 1

In [37]:
df.head()

,Name,Class,Register Number,Gender,Final Position,Event (/5),Clues (/5),First Round (/5),Team Mates Known Prior,Total Members,Same Language,1BSc EA,1BSc DS,3BSc EA,3BSc DS,5BSc EA,5BSc DS,MSc
0,Abhishek Nag,3 BSc DS,21112001,1,Out after Prelims,2.0,3.0,4.0,0,4,0,0,0,0,0,0,0,3
1,Aman Suhag,3 BSc DS,21112003,0,Out after Prelims,4.0,2.0,4.0,2,5,5,0,2,0,2,0,1,0
2,Dhairyashil Mahadik,3 BSc DS,21112006,1,Out after Prelims,2.0,2.0,4.0,0,2,0,0,0,0,1,0,0,0
3,Gaurika,3 BSc DS,21112009,0,Volunteer,4.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0
4,GULAFSHAN,3 BSc DS,21112010,0,Out after Prelims,3.0,3.0,3.0,0,5,0,0,0,0,0,3,0,1

#### One Hot Encoding

In [38]:
# One Hot Encoding 'Final Position' Column
one_hot_encoder_finalpos = OneHotEncoder()
final_position_reshaped = np.array(df['Final Position']).reshape(-1, 1)
final_position_values = one_hot_encoder_finalpos.fit_transform(final_position_reshaped)

In [39]:
final_pos_col = df['Final Position'].unique()
final_position_df = pd.DataFrame(final_position_values.toarray(), columns = final_pos_col)

In [40]:
df_final = pd.concat([df, final_position_df], axis = 1)
df_final = df_final.drop(['Final Position'], axis = 1)

In [41]:
df_final.head()

,Name,Class,Register Number,Gender,Event (/5),Clues (/5),First Round (/5),Team Mates Known Prior,Total Members,Same Language,...,3BSc EA,3BSc DS,5BSc EA,5BSc DS,MSc,Out after Prelims,Volunteer,II Place,III Place,Final Round Contestant
0,Abhishek Nag,3 BSc DS,21112001,1,2.0,3.0,4.0,0,4,0,...,0,0,0,0,3,0.0,0.0,0.0,1.0,0.0
1,Aman Suhag,3 BSc DS,21112003,0,4.0,2.0,4.0,2,5,5,...,0,2,0,1,0,0.0,0.0,0.0,1.0,0.0
2,Dhairyashil Mahadik,3 BSc DS,21112006,1,2.0,2.0,4.0,0,2,0,...,0,1,0,0,0,0.0,0.0,0.0,1.0,0.0
3,Gaurika,3 BSc DS,21112009,0,4.0,1.0,2.0,0,0,0,...,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0
4,GULAFSHAN,3 BSc DS,21112010,0,3.0,3.0,3.0,0,5,0,...,0,0,3,0,1,0.0,0.0,0.0,1.0,0.0

#### Scaling

In [42]:
scaler_one = MinMaxScaler()
df_final[['Event (/5)', 'Clues (/5)', 'First Round (/5)']] = scaler_one.fit_transform(df_final[['Event (/5)', 'Clues (/5)', 'First Round (/5)']])

In [43]:
df_final.head()

,Name,Class,Register Number,Gender,Event (/5),Clues (/5),First Round (/5),Team Mates Known Prior,Total Members,Same Language,...,3BSc EA,3BSc DS,5BSc EA,5BSc DS,MSc,Out after Prelims,Volunteer,II Place,III Place,Final Round Contestant
0,Abhishek Nag,3 BSc DS,21112001,1,0.000000,0.50,0.666667,0,4,0,...,0,0,0,0,3,0.0,0.0,0.0,1.0,0.0
1,Aman Suhag,3 BSc DS,21112003,0,0.666667,0.25,0.666667,2,5,5,...,0,2,0,1,0,0.0,0.0,0.0,1.0,0.0
2,Dhairyashil Mahadik,3 BSc DS,21112006,1,0.000000,0.25,0.666667,0,2,0,...,0,1,0,0,0,0.0,0.0,0.0,1.0,0.0
3,Gaurika,3 BSc DS,21112009,0,0.666667,0.00,0.000000,0,0,0,...,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0
4,GULAFSHAN,3 BSc DS,21112010,0,0.333333,0.50,0.333333,0,5,0,...,0,0,3,0,1,0.0,0.0,0.0,1.0,0.0

#### Normalization

In [44]:
scaler_two = StandardScaler()
df_final[['1BSc EA', '1BSc DS', '3BSc EA', '3BSc DS', '5BSc EA', '5BSc DS']] = scaler_two.fit_transform(df_final[['1BSc EA', '1BSc DS', '3BSc EA', '3BSc DS', '5BSc EA', '5BSc DS']])

In [45]:
df_final.head()

,Name,Class,Register Number,Gender,Event (/5),Clues (/5),First Round (/5),Team Mates Known Prior,Total Members,Same Language,...,3BSc EA,3BSc DS,5BSc EA,5BSc DS,MSc,Out after Prelims,Volunteer,II Place,III Place,Final Round Contestant
0,Abhishek Nag,3 BSc DS,21112001,1,0.000000,0.50,0.666667,0,4,0,...,-0.784465,-0.764866,-0.389640,-0.397360,3,0.0,0.0,0.0,1.0,0.0
1,Aman Suhag,3 BSc DS,21112003,0,0.666667,0.25,0.666667,2,5,5,...,-0.784465,1.664709,-0.389640,1.986799,0,0.0,0.0,0.0,1.0,0.0
2,Dhairyashil Mahadik,3 BSc DS,21112006,1,0.000000,0.25,0.666667,0,2,0,...,-0.784465,0.449921,-0.389640,-0.397360,0,0.0,0.0,0.0,1.0,0.0
3,Gaurika,3 BSc DS,21112009,0,0.666667,0.00,0.000000,0,0,0,...,-0.784465,-0.764866,-0.389640,-0.397360,0,0.0,0.0,0.0,0.0,1.0
4,GULAFSHAN,3 BSc DS,21112010,0,0.333333,0.50,0.333333,0,5,0,...,-0.784465,-0.764866,5.348694,-0.397360,1,0.0,0.0,0.0,1.0,0.0

#### Pandas Profiling

In [47]:
import pandas_profiling

In [48]:
pandas_profiling.ProfileReport(df_final)

Output hidden; open in https://colab.research.google.com to view.

In [49]:
%%shell
jupyter nbconvert --to html /content/21112016_Lab6.ipynb

[NbConvertApp] Converting notebook /content/21112016_Lab6.ipynb to html
[NbConvertApp] Writing 2545833 bytes to /content/21112016_Lab6.html

---------------------------